version: 0.1.{build}
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
cache:
- packages -> **\packages.config
before_build:
- ps: nuget restore .\CouchbaseProviders.sln
build:
  publish_nuget: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  server: https://www.myget.org/F/couchbase-orleans-provider/api/v2/package
  api_key:
    secure: GDE7HrkEv1CxfY5wdjC5lbfMRdfF8soxspbI9NUbGIy4cYOs/+uZqPxzyn9rOUoO
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
